In [1]:
#importar as bibliotecas
from numpy import pi
from numpy import sys
import numpy as np

In [2]:
print('Versão atual do numpy',np.__version__)

Versão atual do numpy 1.18.5


In [3]:
#Função em python para usar no numpy
def f(x, y):
    return 10 * x+y

a = np.fromfunction(f,(5,4), dtype=int)
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [6]:
#Cada coluna na segunda e na terceira linha de a
a[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [9]:
#Obter a ultima linha. Equivalente a a[-1,:]
a[-1]

array([40, 41, 42, 43])

In [11]:
#Uma matriz 3D(duas matrizes 2D empilhadas)
b = np.array([[[ 0,  1,  1],
               [10, 12, 13]],
               [[100, 101, 102],
                [110, 112, 113]]])
b.shape

(2, 2, 3)

In [12]:
# igual a b[1,:,:] ou b[1]
b[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [13]:
b[1,:,:]

array([[100, 101, 102],
       [110, 112, 113]])

In [16]:
b[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [17]:
#Igual a b[:,:, 2]
b[...,2]

array([[  1,  13],
       [102, 113]])

In [19]:
for linha in a:
    print(linha)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [21]:
for elemento in a.flat:
    print(elemento)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
